name: vale-linting
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        config:
          .vale.ini
        onlyAnnotateModifiedLines: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
