name: vale-linting
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Vale
      uses: ./ # Uses an action in the root directory
      with:
        styles: |
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        config:
          .vale.ini
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
